version: '3.8'

services:
  postgres-db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1905
      POSTGRES_DB: Lab
    ports:
      - "5432:5432"
    networks:
      - lab-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: lab-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/Lab
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1905
    depends_on:
      - postgres-db
    networks:
      - lab-network
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./wepApp
      dockerfile: Dockerfile
    container_name: lap-frontend
    ports:
      - "3000:80"
    networks:
      - lab-network
    depends_on:
      - backend

networks:
  lab-network:
